server:
  port: 9719
spring:
  redis:
    database: 0
    host: 118.190.38.37
    port: 6379
    timeout: 1000
    jedis:
      pool:
        max-active: 200
        max-wait: 1
        max-idle: 10
        min-idle: 10