server:
  port: 9719
servlet:
  context-path: /monkey
spring:
  redis:
    database: 0
    host: 118.190.38.37
    port: 6379
    timeout: 1000
    jedis:
      pool:
        max-active: 200
        max-wait: 1
        max-idle: 10
        min-idle: 10
  datasource:
    username: root
    password: smartsmile
    url: jdbc:mysql://118.190.63.96:3306/record?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
  rabbitmq:
    host: 114.55.95.37
    port: 5672
    username: guest
    password: guest
